#! /bin/sh

sxhkd &
killall dunst
dunst &
killall nm-applet
nm-applet &
killall compton
compton -b &
#killall polybar
#~/.config/polybar/launch.sh
#killall flashfocus
#flashfocus &

#background:  #1d1f21
#highlight:   #fb3d66

bspc monitor -d I II III IV V VI 

bspc config border_width        	3
bspc config window_gap          	10
bspc config top_padding		        32

bspc config split_ratio          	0.5
bspc config borderless_monocle   	true
bspc config gapless_monocle      	true
bspc config focus_follows_pointer 	false
bspc config single_monocle	 	    true
bspc config initial_polarity 		second_child

bspc config focused_border_color 	"#ffffff"
bspc config normal_border_color 	"#1d1f21"

bspc config pointer_modifier 		shift
bspc config pointer_action1 		move
bspc config pointer_action2 		resize_corner

bspc rule -a Pavucontrol state=floating 
bspc rule -a xfce4-terminal state=floating 

